name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main  # Set ke branch yang diinginkan, misalnya 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code dari GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Docker Buildx (untuk multi-platform builds jika diperlukan)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login ke Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Ganti dengan secret username Docker Hub Anda
          password: ${{ secrets.DOCKER_PASSWORD }}  # Ganti dengan secret password Docker Hub Anda

      # Build Docker image menggunakan Dockerfile yang ada
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my_image:latest .

      # Push Docker image ke Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my_image:latest
