name: Deploy to Server

on:
  push:
    branches:
      - main # Trigger hanya pada push ke branch `main`

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22 # Gunakan versi Node.js yang sesuai dengan proyek Anda

    - name: Install dependencies
      run: npm install --force

    - name: Build Project
      run: npm run build

    - name: Check if secrets are available
      run: |
        echo "SSH_HOST: ${{ secrets.SSH_HOST }}"
        echo "SSH_PORT: ${{ secrets.SSH_PORT }}"
        echo "SSH_USERNAME: ${{ secrets.SSH_USERNAME }}"
        echo "SSH_USERNAME: ${{ secrets.SSH_PASSWORD }}"

    - name: Deploy to Server
      env:
        HOST: ${{ secrets.SSH_HOST }}
        PORT: ${{ secrets.SSH_PORT }}
        USER: ${{ secrets.SSH_USERNAME }}
        PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        # Login menggunakan SSH (non-interaktif)
        sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no -p $PORT $USER@$HOST << 'EOF'
          # Pindah ke folder gitFile dan install dependencies serta build aplikasi
          cd /var/www/html/devel.kol/gitFile
          git pull
          npm install --force
          npm run build

          # Pindahkan hasil build dari gitFile ke /var/www/html/devel.kol
          cp -r /var/www/html/devel.kol/gitFile/dist/* /var/www/html/devel.kol/

          # Opsional: Menghapus file build setelah dipindahkan
          rm -rf /var/www/html/devel.kol/gitFile/dist/*
        EOF
